### ISSUE TITLE
Installation Directory on Windows

### ISSUE THREAD

**Issue by dope791** [petr-panteleyev/jpackage-maven-plugin#11]
The installation directory on a Windows system **must be a relative path**.

See the jpackage documentation: https://docs.oracle.com/en/java/javase/17/docs/specs/man/jpackage.html#:~:text=%2D%2Dinstall%2Ddir%20%3Cdirectory%20path%3E

This plugin returns an **absolute path** that resolves against the current working directory.
Therefore, the jpackage command cannot resolve the installation directory and considers it invalid.

**Comment by petr-panteleyev** [comment]
Should be fixed in 1.6.1, please check.

**Comment by dope791** [comment]
Thanks for the update.

Unfortunately, I'm running into this errror:

`Failed to execute goal org.panteleyev:jpackage-maven-plugin:1.6.1:jpackage (jpackage) on project cie: Execution jpackage of goal org.panteleyev:jpackage-maven-plugin:1.6.1:jpackage failed: A required class was missing while executing org.panteleyev:jpackage-maven-plugin:1.6.1:jpackage: org/apache/maven/shared/utils/cli/CommandLineException`

I already did remove my Maven repository entries, but still the same issue.

**Comment by petr-panteleyev** [comment]
Pls check 1.6.2

**Comment by dope791** [comment]
Unfortunately I am still getting an absolute path. 

The path already is absolute when arriving in `JPackageMojo.addParamter` (line 981 to 988):

```java
private void addParameter(
            Commandline commandline,
            CommandLineParameter parameter,
            File value,
            boolean checkExistence,
            boolean makeAbsolute,
            int version
    )
```

So the check (`String path = makeAbsolute ? value.getAbsolutePath() : value.getPath();`) does not take effect.

**Comment by petr-panteleyev** [comment]
Made it a String to avoid any transformations. Pls check 1.6.3.

**Comment by dope791** [comment]
Now there is an error in line 1068 with the setter.
Did you compile it?

**Comment by dope791** [comment]
```java
public void setInstallDir(File installDir) {
        this.installDir = installDir;
    }
```

The method not work if `this.installer` is of type `String`.

The error message says: `error: incompatible types: File cannot be converted to String`

**Comment by petr-panteleyev** [comment]
There is no such code in the jpackage-maven-plugin project at all.
Can you please put exact build output here?

**Comment by dope791** [comment]
Never mind, I don't know why my IDE produced this code.
Sorry.

**Comment by dope791** [comment]
Now `--instal-dir` works as expected on Windows. 👍
